//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.09 at 02:06:43 PM CEST 
//


package kendzi.josm.kendzi3d.dto.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kendzi.josm.kendzi3d.dto.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TextureLibrary_QNAME = new QName("http://www.kendzi3d.org", "textureLibrary");
    private final static QName _PointModels_QNAME = new QName("", "pointModels");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kendzi.josm.kendzi3d.dto.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TextureLibrary }
     * 
     */
    public TextureLibrary createTextureLibrary() {
        return new TextureLibrary();
    }

    /**
     * Create an instance of {@link TextureSet }
     * 
     */
    public TextureSet createTextureSet() {
        return new TextureSet();
    }

    /**
     * Create an instance of {@link PointModels }
     * 
     */
    public PointModels createPointModels() {
        return new PointModels();
    }

    /**
     * Create an instance of {@link PointModel }
     * 
     */
    public PointModel createPointModel() {
        return new PointModel();
    }

    /**
     * Create an instance of {@link TextureData }
     * 
     */
    public TextureData createTextureData() {
        return new TextureData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextureLibrary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kendzi3d.org", name = "textureLibrary")
    public JAXBElement<TextureLibrary> createTextureLibrary(TextureLibrary value) {
        return new JAXBElement<TextureLibrary>(_TextureLibrary_QNAME, TextureLibrary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PointModels }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pointModels")
    public JAXBElement<PointModels> createPointModels(PointModels value) {
        return new JAXBElement<PointModels>(_PointModels_QNAME, PointModels.class, null, value);
    }

}
