//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.09 at 11:02:12 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kendzi3d.org")
package kendzi.josm.kendzi3d.dto.xsd;
