//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.06 at 09:31:07 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kendzi3d.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kendzi.josm.kendzi3d.dto.xsd;
