//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.02 at 03:36:09 PM CET 
//


package kendzi.josm.kendzi3d.dto.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TextureData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextureData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="tex0" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tex1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="colorable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextureData")
public class TextureData {

    @XmlAttribute
    protected String tex0;
    @XmlAttribute
    protected String tex1;
    @XmlAttribute
    protected Boolean colorable;
    @XmlAttribute
    protected Double height;
    @XmlAttribute
    protected Double width;

    /**
     * Gets the value of the tex0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTex0() {
        return tex0;
    }

    /**
     * Sets the value of the tex0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTex0(String value) {
        this.tex0 = value;
    }

    /**
     * Gets the value of the tex1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTex1() {
        return tex1;
    }

    /**
     * Sets the value of the tex1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTex1(String value) {
        this.tex1 = value;
    }

    /**
     * Gets the value of the colorable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isColorable() {
        return colorable;
    }

    /**
     * Sets the value of the colorable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setColorable(Boolean value) {
        this.colorable = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHeight(Double value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWidth(Double value) {
        this.width = value;
    }

}
